### ISSUE TITLE
Hi - Ethical Social Media Design

### ISSUE THREAD

**Issue by djk86** [natjms/resin#28]
Hi Nat, I found your blog recently and went through a bunch of your articles, particularly this one:  https://njms.ca/posts/ethical-anti-design.html

You might be interesting in joining up with a few other ethical design advocates, as we have a few projects underway.  I really like what I see with what you are building here so far.  We are trying to build a community of ethically focused, and technology focused people.  If this interests you, there are a few ways to get a hold of me.  I work with www.ruva.app  and droplet.social

**Comment by djk86** [comment]
I'll just ephasize, looking through your links, I didn't have a great way to get a hold of you, but I'd love to have a conversation on this topic with you sometime.  You can see my youtube channel talking about my project here: https://www.youtube.com/channel/UCH_jbNIrie_q2RBW8EZON-A

**Comment by natjms** [comment]
Hey there! Sorry for being so hard to get in touch with; it's been a good while since I've last updated my website. I'll drop you an email and close this issue
