### ISSUE TITLE
Accounting for HTML in user generated content

### ISSUE THREAD

**Issue by natjms** [natjms/resin#9]
The specific circumstances around this issue need more investigation; specifically, the kind of HTML tags that typically show up in someone's bio. They often seem to include paragraph tags in particular.

At this point, if HTML tags show up in a person's bio, they will be rendered as text. Considering how common this is, that's going to make a lot of people's profiles look like a mess. A regex will need to be written to scope these tags out and reformat the content so that it renders correctly in React Native. A nuclear option might be to just remove the unsafe tags and render the content dynamically.

**Comment by mediaformat** [comment]
Just came across [react-native-render-html](https://www.npmjs.com/package/react-native-render-html#basic-usage), might simplify things.

**Comment by natjms** [comment]
Yeah, I've only quickly looked over the readme but that package looks like it could really come in handy, especially in sanitizing out dangerous tags. I'll try to take a closer look at it soon. I still need to experiment more with the Mastodon API but by the looks of it HTML tags pop up in most user generated content so this issue might be above the scope of the profile page. Having something more reliable than a regex would be a plus
